name: 'Container Image Changelog'
description: 'Generates a changelog between two container image versions using Skopeo and Cosign'
author: 'hanthor'
inputs:
  family:
    description: 'Image family to generate the changelog for (e.g., bluefin, bluefin-lts, aurora)'
    required: false
    default: 'bluefin'
  images:
    description: 'Override the default image list for the chosen family (space-separated)'
    required: false
  stream:
    description: 'Release stream for auto-discovery (e.g. stable, latest, lts)'
    required: false
  prev_tag:
    description: 'Previous release tag (ignored if stream is set)'
    required: false
  curr_tag:
    description: 'Current release tag (ignored if stream is set)'
    required: false
  handwritten:
    description: 'Optional introductory text for the changelog'
    required: false
  output:
    description: 'Output file path'
    required: false
    default: 'changelog.md'
  output-env:
    description: 'Output environment file path'
    required: false
  json:
    description: 'Output JSON instead of Markdown'
    required: false
    default: 'false'
  verbose:
    description: 'Enable debug logging'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/hanthor/changelog-action:latest'
  args:
    - --family
    - ${{ inputs.family }}
    - ${{ inputs.images && '--images' || '' }}
    - ${{ inputs.images }}
    - ${{ inputs.stream && '--stream' || '' }}
    - ${{ inputs.stream }}
    - ${{ inputs.handwritten && '--handwritten' || '' }}
    - ${{ inputs.handwritten }}
    - --output
    - ${{ inputs.output }}
    - ${{ inputs.output-env && '--output-env' || '' }}
    - ${{ inputs.output-env }}
    - ${{ inputs.json == 'true' && '--json' || '' }}
    - ${{ inputs.verbose == 'true' && '--verbose' || '' }}
    - ${{ !inputs.stream && inputs.prev_tag || '' }}
    - ${{ !inputs.stream && inputs.curr_tag || '' }}
